CREATE TABLE URI (
    id SERIAL PRIMARY KEY,
    domain TEXT,
    path TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(domain, path)
);

CREATE TABLE analytics_performances (
    id SERIAL PRIMARY KEY,
    URI INT NOT NULL REFERENCES URI(id) ON DELETE CASCADE,
    duration INTEGER NOT NULL,
    type TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE analytics_external_links (
    id SERIAL PRIMARY KEY,
    URI INT NOT NULL REFERENCES URI(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);